ERROR - 2024-05-11 13:28:40 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ci4_biblioteca\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\ci4_biblioteca\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'biblioteca', 3306, '', 0)
#1 C:\xampp\htdocs\ci4_biblioteca\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4_biblioteca\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4_biblioteca\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4_biblioteca\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4_biblioteca\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\ci4_biblioteca\app\Controllers\Autor.php(18): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\ci4_biblioteca\system\CodeIgniter.php(941): App\Controllers\Autor->index()
#8 C:\xampp\htdocs\ci4_biblioteca\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Autor))
#9 C:\xampp\htdocs\ci4_biblioteca\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ci4_biblioteca\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\ci4_biblioteca\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ci4_biblioteca\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4_biblioteca\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4_biblioteca\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4_biblioteca\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4_biblioteca\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4_biblioteca\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\ci4_biblioteca\app\Controllers\Autor.php(18): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\ci4_biblioteca\system\CodeIgniter.php(941): App\Controllers\Autor->index()
#7 C:\xampp\htdocs\ci4_biblioteca\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Autor))
#8 C:\xampp\htdocs\ci4_biblioteca\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4_biblioteca\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\ci4_biblioteca\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2024-05-11 13:28:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `autor`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Autor.php(18): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Autor->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Autor))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\ci4_biblioteca\\public\\index.php')
ERROR - 2024-05-11 13:43:19 --> mysqli_sql_exception: Unknown column 'titulo' in 'field list' in C:\xampp\htdocs\ci4_biblioteca\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4_biblioteca\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `ob...', 0)
#1 C:\xampp\htdocs\ci4_biblioteca\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ob...')
#2 C:\xampp\htdocs\ci4_biblioteca\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ob...')
#3 C:\xampp\htdocs\ci4_biblioteca\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ob...', Array, false)
#4 C:\xampp\htdocs\ci4_biblioteca\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ci4_biblioteca\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ci4_biblioteca\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\ci4_biblioteca\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\ci4_biblioteca\app\Controllers\Obra.php(34): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\ci4_biblioteca\system\CodeIgniter.php(941): App\Controllers\Obra->cadastrar()
#10 C:\xampp\htdocs\ci4_biblioteca\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Obra))
#11 C:\xampp\htdocs\ci4_biblioteca\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ci4_biblioteca\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ci4_biblioteca\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-05-11 13:43:19 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'titulo' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `obra` (`titulo`, `categoria`, `ano_publicacao`, `isbn`, `id_editora`) VALUES (:titulo:, :categoria:, :ano_publicacao:, :isbn:, :id_editora:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Obra.php(34): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Obra->cadastrar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Obra))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\ci4_biblioteca\\public\\index.php')
CRITICAL - 2024-05-11 13:43:19 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'titulo' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `obra` (`titulo`, `categoria`, `ano_publicacao`, `isbn`, `id_editora`) VALUES (\'Alice no País das Maravilha\', \'Literatura fantástica, Literatura nonsense\', \'1865\', \' 8594541759\', \'Selecione uma editora...\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `obra` (`titulo`, `categoria`, `ano_publicacao`, `isbn`, `id_editora`) VALUES (\'Alice no País das Maravilha\', \'Literatura fantástica, Literatura nonsense\', \'1865\', \' 8594541759\', \'Selecione uma editora...\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `obra` (`titulo`, `categoria`, `ano_publicacao`, `isbn`, `id_editora`) VALUES (:titulo:, :categoria:, :ano_publicacao:, :isbn:, :id_editora:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Obra.php(34): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Obra->cadastrar()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Obra))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\ci4_biblioteca\\public\\index.php')
CRITICAL - 2024-05-11 13:43:19 --> [Caused by] mysqli_sql_exception: Unknown column 'titulo' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `obra` (`titulo`, `categoria`, `ano_publicacao`, `isbn`, `id_editora`) VALUES (\'Alice no País das Maravilha\', \'Literatura fantástica, Literatura nonsense\', \'1865\', \' 8594541759\', \'Selecione uma editora...\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `obra` (`titulo`, `categoria`, `ano_publicacao`, `isbn`, `id_editora`) VALUES (\'Alice no País das Maravilha\', \'Literatura fantástica, Literatura nonsense\', \'1865\', \' 8594541759\', \'Selecione uma editora...\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `obra` (`titulo`, `categoria`, `ano_publicacao`, `isbn`, `id_editora`) VALUES (\'Alice no País das Maravilha\', \'Literatura fantástica, Literatura nonsense\', \'1865\', \' 8594541759\', \'Selecione uma editora...\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `obra` (`titulo`, `categoria`, `ano_publicacao`, `isbn`, `id_editora`) VALUES (:titulo:, :categoria:, :ano_publicacao:, :isbn:, :id_editora:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Obra.php(34): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Obra->cadastrar()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Obra))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\ci4_biblioteca\\public\\index.php')
ERROR - 2024-05-11 13:44:28 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`biblioteca`.`obra`, CONSTRAINT `obra_ibfk_1` FOREIGN KEY (`id_editora`) REFERENCES `editora` (`id`)) in C:\xampp\htdocs\ci4_biblioteca\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4_biblioteca\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `ob...', 0)
#1 C:\xampp\htdocs\ci4_biblioteca\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ob...')
#2 C:\xampp\htdocs\ci4_biblioteca\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ob...')
#3 C:\xampp\htdocs\ci4_biblioteca\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ob...', Array, false)
#4 C:\xampp\htdocs\ci4_biblioteca\system\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\ci4_biblioteca\system\BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\ci4_biblioteca\system\Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\ci4_biblioteca\system\BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\ci4_biblioteca\app\Controllers\Obra.php(34): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\ci4_biblioteca\system\CodeIgniter.php(941): App\Controllers\Obra->cadastrar()
#10 C:\xampp\htdocs\ci4_biblioteca\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Obra))
#11 C:\xampp\htdocs\ci4_biblioteca\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\ci4_biblioteca\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\ci4_biblioteca\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-05-11 13:44:28 --> CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`biblioteca`.`obra`, CONSTRAINT `obra_ibfk_1` FOREIGN KEY (`id_editora`) REFERENCES `editora` (`id`))
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `obra` (`titulo`, `categoria`, `ano_publicacao`, `isbn`, `id_editora`) VALUES (:titulo:, :categoria:, :ano_publicacao:, :isbn:, :id_editora:)', [...], false)
 2 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Obra.php(34): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Obra->cadastrar()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Obra))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\ci4_biblioteca\\public\\index.php')
CRITICAL - 2024-05-11 13:44:28 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Cannot add or update a child row: a foreign key constraint fails (`biblioteca`.`obra`, CONSTRAINT `obra_ibfk_1` FOREIGN KEY (`id_editora`) REFERENCES `editora` (`id`))
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `obra` (`titulo`, `categoria`, `ano_publicacao`, `isbn`, `id_editora`) VALUES (\'Alice no País das Maravilha\', \'Literatura fantástica, Literatura nonsense\', \'1865\', \' 8594541759\', \'Selecione uma editora...\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `obra` (`titulo`, `categoria`, `ano_publicacao`, `isbn`, `id_editora`) VALUES (\'Alice no País das Maravilha\', \'Literatura fantástica, Literatura nonsense\', \'1865\', \' 8594541759\', \'Selecione uma editora...\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `obra` (`titulo`, `categoria`, `ano_publicacao`, `isbn`, `id_editora`) VALUES (:titulo:, :categoria:, :ano_publicacao:, :isbn:, :id_editora:)', [...], false)
 4 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\Obra.php(34): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Obra->cadastrar()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Obra))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\ci4_biblioteca\\public\\index.php')
CRITICAL - 2024-05-11 13:44:28 --> [Caused by] mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`biblioteca`.`obra`, CONSTRAINT `obra_ibfk_1` FOREIGN KEY (`id_editora`) REFERENCES `editora` (`id`))
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `obra` (`titulo`, `categoria`, `ano_publicacao`, `isbn`, `id_editora`) VALUES (\'Alice no País das Maravilha\', \'Literatura fantástica, Literatura nonsense\', \'1865\', \' 8594541759\', \'Selecione uma editora...\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `obra` (`titulo`, `categoria`, `ano_publicacao`, `isbn`, `id_editora`) VALUES (\'Alice no País das Maravilha\', \'Literatura fantástica, Literatura nonsense\', \'1865\', \' 8594541759\', \'Selecione uma editora...\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `obra` (`titulo`, `categoria`, `ano_publicacao`, `isbn`, `id_editora`) VALUES (\'Alice no País das Maravilha\', \'Literatura fantástica, Literatura nonsense\', \'1865\', \' 8594541759\', \'Selecione uma editora...\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `obra` (`titulo`, `categoria`, `ano_publicacao`, `isbn`, `id_editora`) VALUES (:titulo:, :categoria:, :ano_publicacao:, :isbn:, :id_editora:)', [...], false)
 5 SYSTEMPATH\Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Obra.php(34): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Obra->cadastrar()
11 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Obra))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\ci4_biblioteca\\public\\index.php')
CRITICAL - 2024-05-11 13:55:08 --> ErrorException: Undefined array key "Titulo"
in APPPATH\Views\obra\edit.php on line 83.
 1 APPPATH\Views\obra\edit.php(83): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "Titulo"', 'C:\\xampp\\htdocs\\ci4_biblioteca\\app\\Views\\obra\\edit.php', 83)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\ci4_biblioteca\\app\\Views\\obra\\edit.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('obra/edit', [], true)
 5 APPPATH\Controllers\Obra.php(43): view('obra/edit', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Obra->editar('2')
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Obra))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\ci4_biblioteca\\public\\index.php')
CRITICAL - 2024-05-11 13:55:33 --> ErrorException: Undefined array key "ano-publicacao"
in APPPATH\Views\obra\edit.php on line 83.
 1 APPPATH\Views\obra\edit.php(83): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "ano-publicacao"', 'C:\\xampp\\htdocs\\ci4_biblioteca\\app\\Views\\obra\\edit.php', 83)
 2 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\ci4_biblioteca\\app\\Views\\obra\\edit.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('obra/edit', [], true)
 5 APPPATH\Controllers\Obra.php(43): view('obra/edit', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Obra->editar('2')
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Obra))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\ci4_biblioteca\\public\\index.php')
